/* Generated by native_observation_profile_contract.py. */
#ifndef MIEL_NATIVE_OBSERVATION_PROFILES_GENERATED_H
#define MIEL_NATIVE_OBSERVATION_PROFILES_GENERATED_H

#define MVOP_CONTRACT_SHA256 "fd0ae453250025c72c46781ed509c6401a4aecd9220a0ab655895469da2551ad"
#define MVOP_SEMANTIC_ID "production-semantic-v1"
#define MVOP_SEMANTIC_OBSERVER_PROFILE "scenario-bounded"
#define MVOP_SEMANTIC_PROFILE_SHA256 "d32973834719055456f82d8e07d0497ed623703dad63c82487d2caf9f538b702"
#define MVOP_SEMANTIC_OMIT_MASK 0x1fffu
#define MVOP_SEMANTIC_OBSERVER_OMITTED_CHANNELS_JSON "[\"particle-lifecycle\",\"presentation-render\",\"shadow-render\"]"
#define MVOP_SEMANTIC_APPLICABLE_RECEIPT_CHANNELS_JSON "[\"semantic\",\"runtime_initial_state\",\"flight_activation_rng\",\"flight_activation_clock\"]"
#define MVOP_SEMANTIC_OMITTED_RECEIPT_CHANNELS_JSON "[\"framebuffer\",\"particle_activation\",\"particle_lifecycle\",\"render_presentation\",\"shadow_render\",\"shadow_camera_render\",\"shadow_render_room\",\"shadow_visible_objects\",\"shadow_visible_polygons\",\"shadow_polygon_render\",\"shadow_world_relation\",\"shadow_rotation_setter\"]"
#define MVOP_SEMANTIC_FRAMEBUFFER_REQUIRED 0
#define MVOP_SEMANTIC_EVIDENCE_ELIGIBLE 1

#define MVOP_VISUAL_ID "full-visual-pixel-v1"
#define MVOP_VISUAL_OBSERVER_PROFILE "full"
#define MVOP_VISUAL_PROFILE_SHA256 "df98ac196d8c842c41e26e62ff25868afe6a78b78f3e2ce5f9a381af191f6142"
#define MVOP_VISUAL_OMIT_MASK 0x0000u
#define MVOP_VISUAL_OBSERVER_OMITTED_CHANNELS_JSON "[]"
#define MVOP_VISUAL_APPLICABLE_RECEIPT_CHANNELS_JSON "[\"semantic\",\"runtime_initial_state\",\"flight_activation_rng\",\"flight_activation_clock\",\"framebuffer\",\"particle_activation\",\"particle_lifecycle\",\"render_presentation\",\"shadow_render\",\"shadow_camera_render\",\"shadow_render_room\",\"shadow_visible_objects\",\"shadow_visible_polygons\",\"shadow_polygon_render\",\"shadow_world_relation\",\"shadow_rotation_setter\"]"
#define MVOP_VISUAL_OMITTED_RECEIPT_CHANNELS_JSON "[]"
#define MVOP_VISUAL_FRAMEBUFFER_REQUIRED 1
#define MVOP_VISUAL_EVIDENCE_ELIGIBLE 1

#endif
