#!/usr/bin/env python3
"""Generate the shared native observation-profile JSON and C contract."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
JSON_PATH = ROOT / "content/miel_vliegt/native_observation_profiles.json"
HEADER_PATH = (
    ROOT / "tools/miel_vliegt/hangover/native_observation_profiles.generated.h"
)
PROTOCOL = "miel-vliegt-native-observation-profile-contract"
PROFILE_PROTOCOL = "miel-vliegt-native-scenario-observation-profile"
VISUAL_SCENARIO = "default-airplane-fixed-camera-frame"
SCENARIO_IDS = (
    "controls-press-hold-release",
    "taxi-straight",
    "takeoff-climb",
    "level-flight-turn",
    "approach-landing",
    "impact-crash",
    VISUAL_SCENARIO,
)
RECEIPT_CHANNELS = (
    "semantic",
    "runtime_initial_state",
    "flight_activation_rng",
    "flight_activation_clock",
    "framebuffer",
    "particle_activation",
    "particle_lifecycle",
    "render_presentation",
    "shadow_render",
    "shadow_camera_render",
    "shadow_render_room",
    "shadow_visible_objects",
    "shadow_visible_polygons",
    "shadow_polygon_render",
    "shadow_world_relation",
    "shadow_rotation_setter",
)
SEMANTIC_RECEIPT_CHANNELS = RECEIPT_CHANNELS[:4]
VISUAL_OBSERVER_CHANNELS = (
    "particle-lifecycle",
    "presentation-render",
    "shadow-render",
)


class ObservationProfileContractError(ValueError):
    """The generated observation-profile contract is invalid or stale."""


def _canonical(value: Any) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ).encode("ascii")


def _sha256(value: Any) -> str:
    return hashlib.sha256(_canonical(value)).hexdigest()


def _profile(
    identifier: str,
    observer_profile: str,
    omit_mask: str,
    observer_omitted_channels: tuple[str, ...],
    applicable_receipt_channels: tuple[str, ...],
    framebuffer_required: bool,
) -> dict[str, Any]:
    applicable = list(applicable_receipt_channels)
    value = {
        "schema": 1,
        "protocol": PROFILE_PROTOCOL,
        "id": identifier,
        "observer_profile": observer_profile,
        "omit_mask": omit_mask,
        "observer_omitted_channels": list(observer_omitted_channels),
        "applicable_receipt_channels": applicable,
        "omitted_receipt_channels": [
            channel for channel in RECEIPT_CHANNELS
            if channel not in applicable_receipt_channels
        ],
        "framebuffer_required": framebuffer_required,
        "parity_evidence_eligible": True,
        "evidence_blocker": None,
    }
    return {**value, "profile_sha256": _sha256(value)}


def contract_value() -> dict[str, Any]:
    profiles = (
        _profile(
            "production-semantic-v1",
            "scenario-bounded",
            "0x1fff",
            VISUAL_OBSERVER_CHANNELS,
            SEMANTIC_RECEIPT_CHANNELS,
            False,
        ),
        _profile(
            "full-visual-pixel-v1",
            "full",
            "0x0000",
            (),
            RECEIPT_CHANNELS,
            True,
        ),
    )
    identity = {
        "schema": 1,
        "protocol": PROTOCOL,
        "profiles": list(profiles),
        "scenario_profiles": {
            scenario_id: (
                "full-visual-pixel-v1"
                if scenario_id == VISUAL_SCENARIO
                else "production-semantic-v1"
            )
            for scenario_id in SCENARIO_IDS
        },
    }
    return {**identity, "contract_sha256": _sha256(identity)}


def render_json() -> bytes:
    return _canonical(contract_value()) + b"\n"


def _c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def _c_json(value: Any) -> str:
    return _c_string(_canonical(value).decode("ascii"))


def render_header() -> bytes:
    contract = contract_value()
    profiles = {profile["id"]: profile for profile in contract["profiles"]}
    semantic = profiles["production-semantic-v1"]
    visual = profiles["full-visual-pixel-v1"]
    lines = [
        "/* Generated by native_observation_profile_contract.py. */",
        "#ifndef MIEL_NATIVE_OBSERVATION_PROFILES_GENERATED_H",
        "#define MIEL_NATIVE_OBSERVATION_PROFILES_GENERATED_H",
        "",
        f"#define MVOP_CONTRACT_SHA256 "
        f"{_c_string(contract['contract_sha256'])}",
        f"#define MVOP_SEMANTIC_ID {_c_string(semantic['id'])}",
        f"#define MVOP_SEMANTIC_OBSERVER_PROFILE "
        f"{_c_string(semantic['observer_profile'])}",
        f"#define MVOP_SEMANTIC_PROFILE_SHA256 "
        f"{_c_string(semantic['profile_sha256'])}",
        f"#define MVOP_SEMANTIC_OMIT_MASK {semantic['omit_mask']}u",
        f"#define MVOP_SEMANTIC_OBSERVER_OMITTED_CHANNELS_JSON "
        f"{_c_json(semantic['observer_omitted_channels'])}",
        f"#define MVOP_SEMANTIC_APPLICABLE_RECEIPT_CHANNELS_JSON "
        f"{_c_json(semantic['applicable_receipt_channels'])}",
        f"#define MVOP_SEMANTIC_OMITTED_RECEIPT_CHANNELS_JSON "
        f"{_c_json(semantic['omitted_receipt_channels'])}",
        f"#define MVOP_SEMANTIC_FRAMEBUFFER_REQUIRED "
        f"{1 if semantic['framebuffer_required'] else 0}",
        f"#define MVOP_SEMANTIC_EVIDENCE_ELIGIBLE "
        f"{1 if semantic['parity_evidence_eligible'] else 0}",
        "",
        f"#define MVOP_VISUAL_ID {_c_string(visual['id'])}",
        f"#define MVOP_VISUAL_OBSERVER_PROFILE "
        f"{_c_string(visual['observer_profile'])}",
        f"#define MVOP_VISUAL_PROFILE_SHA256 "
        f"{_c_string(visual['profile_sha256'])}",
        f"#define MVOP_VISUAL_OMIT_MASK {visual['omit_mask']}u",
        f"#define MVOP_VISUAL_OBSERVER_OMITTED_CHANNELS_JSON "
        f"{_c_json(visual['observer_omitted_channels'])}",
        f"#define MVOP_VISUAL_APPLICABLE_RECEIPT_CHANNELS_JSON "
        f"{_c_json(visual['applicable_receipt_channels'])}",
        f"#define MVOP_VISUAL_OMITTED_RECEIPT_CHANNELS_JSON "
        f"{_c_json(visual['omitted_receipt_channels'])}",
        f"#define MVOP_VISUAL_FRAMEBUFFER_REQUIRED "
        f"{1 if visual['framebuffer_required'] else 0}",
        f"#define MVOP_VISUAL_EVIDENCE_ELIGIBLE "
        f"{1 if visual['parity_evidence_eligible'] else 0}",
        "",
        "#endif",
        "",
    ]
    return "\n".join(lines).encode("ascii")


def _validate_profile(profile: Any) -> dict[str, Any]:
    if not isinstance(profile, dict):
        raise ObservationProfileContractError("observation profile must be an object")
    fields = {
        "schema", "protocol", "id", "observer_profile", "omit_mask",
        "observer_omitted_channels", "applicable_receipt_channels",
        "omitted_receipt_channels", "framebuffer_required",
        "parity_evidence_eligible", "evidence_blocker", "profile_sha256",
    }
    if set(profile) != fields:
        raise ObservationProfileContractError("observation profile fields drifted")
    identity = {
        key: value for key, value in profile.items()
        if key != "profile_sha256"
    }
    if profile["profile_sha256"] != _sha256(identity):
        raise ObservationProfileContractError("observation profile SHA drifted")
    return profile


def load_contract(path: Path = JSON_PATH) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="ascii"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ObservationProfileContractError(
            "native observation-profile contract is unavailable"
        ) from error
    expected = contract_value()
    if _canonical(value) != _canonical(expected):
        raise ObservationProfileContractError(
            "native observation-profile contract drifted"
        )
    for profile in value["profiles"]:
        _validate_profile(profile)
    return value


def profile_for_scenario(scenario_id: str) -> dict[str, Any]:
    contract = load_contract()
    try:
        profile_id = contract["scenario_profiles"][scenario_id]
    except KeyError as error:
        raise ObservationProfileContractError(
            f"unknown observation-profile scenario: {scenario_id!r}"
        ) from error
    matches = [
        profile for profile in contract["profiles"]
        if profile["id"] == profile_id
    ]
    if len(matches) != 1:
        raise ObservationProfileContractError(
            "scenario observation-profile mapping is ambiguous"
        )
    return dict(matches[0])


def check_generated() -> None:
    if JSON_PATH.read_bytes() != render_json():
        raise ObservationProfileContractError(
            "native observation-profile JSON is stale"
        )
    if HEADER_PATH.read_bytes() != render_header():
        raise ObservationProfileContractError(
            "native observation-profile C header is stale"
        )
    load_contract()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        check_generated()
        print(f"PASS {JSON_PATH}")
        print(f"PASS {HEADER_PATH}")
        return 0
    JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    JSON_PATH.write_bytes(render_json())
    HEADER_PATH.write_bytes(render_header())
    print(contract_value()["contract_sha256"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
